apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-api
  namespace: staging
  labels:
    app: mini-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-api
  template:
    metadata:
      labels:
        app: mini-api
    spec:
      containers:
        - name: mini-api
          image: ghcr.io/snwnw/ssrd-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
